spring.application.name=reactFilmeMobile

spring.datasource.url=${APP_DB_URL:jdbc:h2:mem:filmesdb;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${APP_DB_USER:sa}
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

auth.jwt-secret=8ec6237a0f78cd78313740b945f315196a45e9f61f2cf55987650298fb1c3cae
auth.jwt-expiration=86400000

